//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesPerson.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class commission
    {
        public int commissionId { get; set; }
        public int personId { get; set; }
        public decimal southern { get; set; }
        public decimal coastal { get; set; }
        public decimal northern_ { get; set; }
        public decimal eastern { get; set; }
        public decimal Lebanon { get; set; }
        public decimal commission1 { get; set; }
        public Nullable<int> month { get; set; }
        public Nullable<int> year { get; set; }
    
        public virtual salesPerson salesPerson { get; set; }
    }
}
