//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesPerson.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class salesPerson
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public salesPerson()
        {
            this.commission = new HashSet<commission>();
        }
    
        public int personId { get; set; }
        public int personNumber { get; set; }
        public string personName { get; set; }
        public string personPassword { get; set; }
        public string image { get; set; }
        public System.DateTime registrationDate { get; set; }
        public int personRegionId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<commission> commission { get; set; }
        public virtual region region { get; set; }
    }
}
